spring.application.name=Employee Manager

spring.datasource.url=jdbc:postgresql://localhost:5332/employeemanager
spring.datasource.username=amigoscode
spring.datasource.password=password
spring.datasource.dbcp2.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update